### ISSUE TITLE
Modpack url

### ISSUE THREAD

**Issue by bochen415** [almostwhitehat/tekkit-mod#1]
I just made a test zip modpack with the link to your repo and it worked. The launcher downloaded it fine.

The link you need is:
https://codeload.github.com/almostwhitehat/tekkit-mod/zip/master

**Comment by almostwhitehat** [comment]
It's really odd... if you use the github archive link, technic launcher will act as if it successfully downloaded - but none of the mods are installed. If you go into to the root directory where it should have extracted the archive, the mods and config folder are empty.

It also has a tekkit-mod-master folder, which has the contents of my archive that should have been extracted into the other folders.

I've only done this on osx - I'm not sure what happens on windows. I'm wondering if maybe technic is relying on the OS to extract the archive - and in osx, the default action is to put the contents into a folder with the same name as the archive.

I'm going to close this issue out, but feel free to reopen it if you have any details on whether it actually put the mods in the right place for you, and which OS you're using.

**Comment by bochen415** [comment]
Damn, it really is in a subdirectory. Welp, the launcher needs the mods and config in the root of the zip file.
